## See: https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions/71489231#71489231
name: Callable Test

on: [ workflow_call ]

jobs:
  lint_and_test:
    name: Lint and test as modern TypeScript / JavaScript module
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '22.x'

    steps:
      - uses: actions/checkout@v4
        with:
          ## See: https://github.com/actions/checkout/issues/1662
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.head_ref }}

      - name: Cache restore
        id: cache-npm-restore
        uses: actions/cache/restore@v4.0.2
        with:
          path: |
            node_modules/
            target/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Update and set tool chain -> ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint source code
        run: npm run lint

      - name: Test source code
        run: npm test

      - name: Cache save
        uses: actions/cache/save@v4.0.2
        with:
          path: |
            node_modules/
            target/
          key: ${{ steps.cache-npm-restore.outputs.cache-primary-key }}


##
# Attributions:
#   - https://doc.rust-lang.org/cargo/guide/continuous-integration.html
#   - https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
#   - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

