name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  lint_and_test:
    uses: ./.github/workflows/callable-test.yaml

  publish:
    name: Publish - Guarded Set Interval
    needs: [ lint_and_test ]
    runs-on: ubuntu-latest
    ## See: https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ## See: https://github.com/actions/checkout/issues/1662
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.head_ref }}

      - name: Ensure versions from Package JSON and Git are identical
        run: |
          PACKAGE_VERSION="v$(awk '/version/ { gsub("[,\"]", ""); print $2; }' package.json )"
          GIT_TAG_VERSION="$(git tag --list --sort -creatordate v* | tail -1)"

          if [[ "${PACKAGE_VERSION}" != "${GIT_TAG_VERSION}" ]]; then 
            cat >&2 <<EOF
            Error: Package and Git versions do not match
            PACKAGE_VERSION  ->  ${PACKAGE_VERSION}
            GIT_TAG_VERSION  ->  ${GIT_TAG_VERSION}
          EOF
            exit 1
          fi

      - name: Cache restore
        id: cache-npm-restore
        uses: actions/cache/restore@v4.0.2
        with:
          path: |
            node_modules/
            target/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node for publishing
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Transpile TypeScript into JavaScript
        run: npm run build.all

      - name: Publish dry run
        run: npm run publish --dry-run

      - name: Publish for real
        run: npm run publish --provenance --access public


      - name: Cache save
        uses: actions/cache/save@v4.0.2
        with:
          path: |
            node_modules/
            target/
          key: ${{ steps.cache-npm-restore.outputs.cache-primary-key }}

##
# Attributions:
#   - https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

