name: Test

on:
  pull_request:
    branches: [ main ]
    paths:
      - ./github/workflows/**/*.yaml
      - src/**/*.ts
      - tests/**/*.ts

  ## TODO: maybe prevent running when `tag` is published
  push:
    branches: [ main ]
    paths:
      - .github/workflows/**/*.yaml
      - src/**/*.ts
      - tests/**/*.ts

jobs:
  lint_and_test:
    uses: ./.github/workflows/callable-test.yaml

